### ISSUE TITLE
SDXL support?

### ISSUE THREAD

**Issue by kabachuha** [Nota-NetsPresso/BK-SDM#17]
Hi there!

I'd like to ask, do you have or plan to have support for the SDXL model? It's quite heavy and the process of making it more fast and lightweights would have insane benefits to the community.

Thanks for your work!

**Comment by bokyeong1015** [comment]
Hi, thank you for your interest!

Our current focus is on different projects, and SDXL hasn't been scheduled yet.
However, we totally agree with your point and will happily reach out if we dive into SDXL.
