### ISSUE TITLE
Is it possible to fine-tune it for inpainting/outpainting task

### ISSUE THREAD

**Issue by Bikesuffer** [Nota-NetsPresso/BK-SDM#2]
Do you guys have any plan to fine-tune it for inpainting?

Thanks.

**Comment by bokyeong1015** [comment]
Hi,

Thank you for your interest. We don't have any plans yet, due to our current focus on other works.

**Comment by Bikesuffer** [comment]
> Hi,
> 
> Thank you for your interest. We don't have any plans yet, due to our current focus on other works.

thanks
