### ISSUE TITLE
issue about training iterations

### ISSUE THREAD

**Issue by StormArcher** [Nota-NetsPresso/BK-SDM#49]
We note the readme show training BK-SDM-Base need 50K interations， while we find in the "kd_train.py" show  --max_train_steps=400K \, so can we think the 50K is good enough?

**Comment by bokyeong1015** [comment]
Hi,

Although [our script](https://github.com/Nota-NetsPresso/BK-SDM/blob/6e3a3353140fa7a26d97b435da888e295145321e/scripts/kd_train.sh#L31) specifies --max_train_steps=400000, we released **the checkpoints at the exact 50000-th step** as described in our paper.

Evaluating at 50K iterations was primarily done to reduce training costs (while yielding acceptable performance). Extending the number of iterations and using more data could lead to improved results.

For more details, please refer to the table below in [our paper](https://arxiv.org/abs/2305.15798).
![image](https://github.com/Nota-NetsPresso/BK-SDM/assets/15525982/f82b45d5-9f10-4bf0-b482-15164b647a21).
