### ISSUE TITLE
We find the 2.3M dataset can not download, the link is wrong?

### ISSUE THREAD

**Issue by StormArcher** [Nota-NetsPresso/BK-SDM#50]
1 we can download the 212K dataset by 
 https://netspresso-research-code-release.s3.us-east-2.amazonaws.com/data/improved_aesthetics_6.5plus/preprocessed_212k.tar.gz
 but the 2.3M dataset cannot
 https://netspresso-research-code-release.s3.us-east-2.amazonaws.com/data/improved_aesthetics_6.5plus/preprocessed_2256k.tar.gz

2 we also try "bash " method
bash scripts/get_laion_data.sh preprocessed_2256k

**Comment by bokyeong1015** [comment]
Hi, could you try out the below link, as described in [our script](https://github.com/Nota-NetsPresso/BK-SDM/blob/main/scripts/get_laion_data.sh#L21) (bash scripts/get_laion_data.sh preprocessed_2256k)?

https://netspresso-research-code-release.s3.us-east-2.amazonaws.com/data/improved_aesthetics_6.25plus/preprocessed_2256k.tar.gz

For the link you used, there is a typo: `6.5plus` -> `6.25plus` for the 2.3M dataset.
