### ISSUE TITLE
Queries 

### ISSUE THREAD

**Issue by abhigoku10** [Nota-NetsPresso/BK-SDM#56]
@bokyeong1015  hi thanks for sharing this wonderful work , i had few queries and request 

1. Can you please share ur checkpoint-45000 on one drive or google drive , i wanted to test it on the system as donot have the resources to train it on gpu system 
2. In ur paper u have mentioned deploying on Nvidia orin ? did u test it on any other platforms like Nvidia Agx / Nx/ nano if so whats the time taken on it 
3. When deploying it on nvidia orin did u used docker or straight up with hugging face models 
4. The Techniques used in this paper and the snap fusion can we bring in those in this code and can we expect to see some better improvements 
5. 
![image](https://github.com/Nota-NetsPresso/BK-SDM/assets/22094053/26c14b49-f294-4eb2-a5f4-f358114289fc)

Thanks n advanc

**Comment by deepkyu** [comment]
Sorry for late late reply @abhigoku10 

For question 3, we utilized stable diffusion webui code and a Docker environment on NVIDIA Jetson, provided by [dusty-nv/jetson-containers](https://github.com/dusty-nv/jetson-containers). We updated the model code to support both the original stable diffusion and our BK-SDM. The model checkpoint is the same as the one available on Hugging Face, but it requires remapping the module name.

**Comment by bokyeong1015** [comment]
Hi,

- (1) We would recommend using [our uploaded models on Hugging Face Spaces](https://huggingface.co/collections/nota-ai/efficient-stable-diffusion-66360f7a8ec495f0cd12d1ff), which are checkpoint-50000.
- (2) We deployed our models on the NVIDIA AGX Orin 32GB device. Testing on other NVIDIA edge GPUs has not been planned yet.
- (4) Thanks for the comment, but compressing the image decoder has not been scheduled yet. In our recent work (titled [EdgeFusion](https://arxiv.org/abs/2404.11925)), the BK-SDM-Tiny model was combined with LCM for few-step generation.
