### ISSUE TITLE
ValueError: Invalid pattern: '**' can only be an entire path component

### ISSUE THREAD

**Issue by Saranga7** [Nota-NetsPresso/BK-SDM#58]
pip install -U datasets

This solves the issue of loading the data.

**Comment by bokyeong1015** [comment]
Hi, thanks for your comment. It would be very helpful if you could provide the script you used and describe the issue in detail.

**Comment by Lyrilon** [comment]
but why it works.....another version problem?

**Comment by Saranga7** [comment]
It was a version problem yes.
