### ISSUE TITLE
How to replicate this work offline

### ISSUE THREAD

**Issue by pj666-e** [Nota-NetsPresso/BK-SDM#60]
Hi,thanks for your great work!
I currently have an A100 GPU server that is not connected to the internet. I can configure the environment offline. **Can I replicate your work offline?**Could you please provide me with some guidance? Thank you.

**Comment by deepkyu** [comment]
Hi @pj666-e , sorry for late response.
Currently, training code with diffusers, transformers, and huggingface_hub is hard to run without internet connection. I'm not sure but there are some functions needed internet connection.

For inference, you could refer to our [Hugging Face Spaces Demo](https://huggingface.co/spaces/nota-ai/compressed-stable-diffusion) to check how model checkpoints are loaded. In our experience, if the checkpoint is cached at first, it works without internet connection.

Hope it helps!

**Comment by pj666-e** [comment]
Thank you very much for your reply. I have resolved the issue now. Thanks again for your help, and I wish you success in your work.
