### ISSUE TITLE
Any plan to release v2.1-base model?

### ISSUE THREAD

**Issue by inkzk** [Nota-NetsPresso/BK-SDM#61]

**Comment by bokyeong1015** [comment]
Hi, sorry for the late response. We’ve just released the BK-SDM-v2 models. Please find the links below:
- https://huggingface.co/nota-ai/bk-sdm-v2-base
- https://huggingface.co/nota-ai/bk-sdm-v2-small
- https://huggingface.co/nota-ai/bk-sdm-v2-tiny
